### ISSUE TITLE
zr not working and making game laggy

### ISSUE THREAD

**Issue by Hats-OFF-is-not-available** [Source2ZE/ZombieReborn#64] opened 2023-05-04 12:18 UTC
its making the server laggy
like
every npc is dying including me
and their guns drop to the ground
creating fake circles
and making the game unplayable
[here](https://youtu.be/eQ-cIgLtxZY) is a video i made with the issue replicate
i didnt do anything to the files or the server i basically made an empty folder put a base server and imported all files from the zip file
happens again if i only import  the cfg and scripts folder

**Comment by Vauff** [comment] 2023-06-25 06:08
This was caused by certain `bot_quota_mode` values conflicting with our forceteams implementation. Fixed in https://github.com/Source2ZE/ZombieReborn/commit/17dbe157aeb33a7e4936d968a702fa6700dea3d8 by enforcing `bot_quota_mode fill` in plugin.

**Closed by Vauff** 2023-06-25 06:08 UTC

**Comment by lucianene** [comment] 2026-08-17 10:12
I submited a pr on this.
